package NoteInterfaceModule;

/**
* NoteInterfaceModule/NoteInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NoteInterface.idl
* Friday, November 19, 2021 11:09:21 AM CET
*/

public final class NoteInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public NoteInterfaceModule.NoteInterface value = null;

  public NoteInterfaceHolder ()
  {
  }

  public NoteInterfaceHolder (NoteInterfaceModule.NoteInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NoteInterfaceModule.NoteInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NoteInterfaceModule.NoteInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NoteInterfaceModule.NoteInterfaceHelper.type ();
  }

}
