package NoteInterfaceModule;


/**
* NoteInterfaceModule/NoteInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NoteInterface.idl
* Friday, November 19, 2021 11:09:21 AM CET
*/

public interface NoteInterface extends NoteInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NoteInterface
