package NoteInterfaceModule;


/**
* NoteInterfaceModule/NoteInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NoteInterface.idl
* Friday, November 19, 2021 11:09:21 AM CET
*/

public interface NoteInterfaceOperations 
{
  double getNote (short cin, String codeMatiere);
  void shutdown ();
} // interface NoteInterfaceOperations
