package NoteInterfaceModule;


/**
* NoteInterfaceModule/NoteInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NoteInterface.idl
* Friday, November 19, 2021 11:09:21 AM CET
*/

abstract public class NoteInterfaceHelper
{
  private static String  _id = "IDL:NoteInterfaceModule/NoteInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, NoteInterfaceModule.NoteInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NoteInterfaceModule.NoteInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NoteInterfaceModule.NoteInterfaceHelper.id (), "NoteInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NoteInterfaceModule.NoteInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NoteInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NoteInterfaceModule.NoteInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static NoteInterfaceModule.NoteInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NoteInterfaceModule.NoteInterface)
      return (NoteInterfaceModule.NoteInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NoteInterfaceModule._NoteInterfaceStub stub = new NoteInterfaceModule._NoteInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static NoteInterfaceModule.NoteInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NoteInterfaceModule.NoteInterface)
      return (NoteInterfaceModule.NoteInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NoteInterfaceModule._NoteInterfaceStub stub = new NoteInterfaceModule._NoteInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
